<!DOCTYPE html>
<html lang="en" class="has-navbar-fixed-top">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>{{ $title }} - SensorBreiten</title>
    <link rel="stylesheet" href="/css/bulma.min.css">
    @if (isset($use_leaflet)):
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.6.0/leaflet.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.6.0/leaflet.js"></script>
    @endif
    @if (isset($use_chart)):
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
    @endif
</head>
<body>
    <div class="navbar is-light is-fixed-top" style="z-index: 999999;">
        <div class="container">
            <div class="navbar-brand">
                <a class="navbar-item has-text-weight-bold" href="{{ route('home') }}">SensorBreiten</a>
                <a class="navbar-burger burger"><span></span><span></span><span></span></a>
            </div>
            <div class="navbar-menu">
                @auth:
                    <div class="navbar-start">
                        @$stations = Stations::all()
                        @if (count($stations ) > 0):
                            <div class="navbar-item has-dropdown is-hoverable">
                                <a class="navbar-link is-arrowless" href="{{ route('stations.index') }}">Stations</a>
                                <div class="navbar-dropdown">
                                    @foreach ($stations as $station):
                                        <a class="navbar-item" href="{{ route('stations.show', $station) }}">{{ $station->name }}</a>
                                    @endforeach
                                </div>
                            </div>
                        @else:
                            <a class="navbar-item" href="{{ route('stations.index') }}">Stations</a>
                        @endif

                        @$events = Events::all()
                        @if (count($events ) > 0):
                            <div class="navbar-item has-dropdown is-hoverable">
                                <a class="navbar-link is-arrowless" href="{{ route('events.index') }}">Events</a>
                                <div class="navbar-dropdown">
                                    @foreach ($events as $event):
                                        <a class="navbar-item" href="{{ route('events.show', $event) }}">{{ $event->name }}</a>
                                    @endforeach
                                </div>
                            </div>
                        @else:
                            <a class="navbar-item" href="{{ route('events.index') }}">Events</a>
                        @endif

                        @if (Auth::user()->role == Users::ROLE_ADMIN):
                            <div class="navbar-item has-dropdown is-hoverable">
                                <a class="navbar-link is-arrowless" href="{{ route('admin.home') }}">Admin</a>
                                <div class="navbar-dropdown">
                                    <a class="navbar-item" href="{{ route('admin.users.index') }}">Users</a>
                                </div>
                            </div>
                        @endif
                    </div>

                    <div class="navbar-end">
                        <div class="navbar-item" style="display: flex; align-items: center;">
                            <img style="border-radius: 50%; margin-right: 12px;" src="https://www.gravatar.com/avatar/{{ md5(Auth::user()->email) }}?s=48&d=mp" alt="{{ Auth::user()->firstname }} {{ Auth::user()->lastname }}'s avatar">
                            <span>{{ Auth::user()->firstname }} {{ Auth::user()->lastname }}</span>
                        </div>
                        <div class="navbar-item">
                            <div class="buttons">
                                <a class="button is-link" href="{{ route('settings') }}">Settings</a>
                                <a class="button" href="{{ route('auth.logout') }}">Logout</a>
                            </div>
                        </div>
                    </div>
                @else:
                    <div class="navbar-end">
                        <div class="navbar-item">
                            <div class="buttons">
                                <a class="button is-link" href="{{ route('auth.login') }}">Login</a>
                            </div>
                        </div>
                    </div>
                @endif
            </div>
        </div>
    </div>

    <div class="section">
        <div class="container">
