<!DOCTYPE html>
<html lang="en" class="has-navbar-fixed-top">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>{{ $title }} - SensorBreiten</title>
    <link rel="stylesheet" href="/css/bulma.min.css">
</head>
<body>
    <div class="navbar is-light is-fixed-top">
        <div class="container">
            <div class="navbar-brand">
                <a class="navbar-item has-text-weight-bold" href="{{ route('home') }}">SensorBreiten</a>
                <a class="navbar-burger burger"><span></span><span></span><span></span></a>
            </div>
            <div class="navbar-menu">
                @auth:
                    <!-- <div class="navbar-start">
                        <a class="navbar-item" href="/">TODO</a>
                    </div> -->

                    <div class="navbar-end">
                        <div class="navbar-item" style="display: flex; align-items: center;">
                            <img style="border-radius: 50%; margin-right: 12px;" src="https://www.gravatar.com/avatar/{{ md5(Auth::user()->email) }}?s=48&d=mp" alt="{{ Auth::user()->firstname }} {{ Auth::user()->lastname }}'s avatar">
                            <span>{{ Auth::user()->firstname }} {{ Auth::user()->lastname }}</span>
                        </div>
                        <div class="navbar-item">
                            <div class="buttons">
                                <a class="button is-link" href="{{ route('settings') }}">Settings</a>
                                <a class="button" href="{{ route('auth.logout') }}">Logout</a>
                            </div>
                        </div>
                    </div>
                @else:
                    <div class="navbar-end">
                        <div class="navbar-item">
                            <div class="buttons">
                                <a class="button is-link" href="{{ route('auth.login') }}">Login</a>
                            </div>
                        </div>
                    </div>
                @endif
            </div>
        </div>
    </div>

    <div class="section">
        <div class="container">
