@view('layout.header', [ 'title' => 'Admin' ])

<div class="breadcrumb">
    <ul>
        <li><a href="{{ route('home') }}">SensorBreiten</a></li>
        <li><a href="{{ route('admin.home') }}">Admin</a></li>
        <li class="is-active"><a href="{{ route('admin.users.index') }}">Users</a></li>
    </ul>
</div>

<div class="content">
    <h1 class="title">Users</h1>

    @if (count($users) > 0):
        <div class="columns is-multiline">
            @foreach ($users as $user):
                <div class="column is-one-third">
                    <div class="box content" style="height: 100%">
                        <h2 class="title is-4">
                            <a href="{{ route('admin.users.show', $user) }}">{{ $user->firstname }} {{ $user->lastname }}</a>

                            @if ($user->role == Users::ROLE_NORMAL):
                                <span class="tag is-pulled-right is-success">NORMAL</span>
                            @endif
                            @if ($user->role == Users::ROLE_MODERATOR):
                                <span class="tag is-pulled-right is-info">MODERATOR</span>
                            @endif
                            @if ($user->role == Users::ROLE_ADMIN):
                                <span class="tag is-pulled-right is-danger">ADMIN</span>
                            @endif
                        </h2>

                        <p><a class="tag" href="mailto:{{ $user->email }}">{{ $user->email }}</a></p>
                    </div>
                </div>
            @endforeach
        </div>
    @else:
        <p><i>There are no users found</i></p>
    @endif

    @if (Auth::user()->role >= Users::ROLE_MODERATOR):
        <div class="buttons">
            <a class="button is-link" href="{{ route('admin.users.create') }}">Create user</a>
        </div>
    @endif
</div>

@view('layout.footer')
